# Generated by Django 5.2.6 on 2025-11-06 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('mood', models.CharField(blank=True, choices=[('happy', '😊 Счастливый'), ('sad', '😢 Грустный'), ('excited', '🤩 Взволнованный'), ('calm', '😌 Спокойный'), ('anxious', '😰 Тревожный'), ('grateful', '🙏 Благодарный'), ('tired', '😴 Усталый'), ('motivated', '💪 Мотивированный')], max_length=20, null=True, verbose_name='Настроение')),
                ('tags', models.CharField(blank=True, max_length=255, verbose_name='Теги (через запятую)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранное')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись дневника',
                'verbose_name_plural': 'Записи дневника',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='diary_app_d_created_69e2df_idx'), models.Index(fields=['user', '-created_at'], name='diary_app_d_user_id_b4770e_idx')],
            },
        ),
    ]
