# Generated by Django 5.2.6 on 2025-11-06 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='diary_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diary_app.diaryentry', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Изображение записи',
                'verbose_name_plural': 'Изображения записей',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
